### ISSUE TITLE
Stacktrace with newer version 4.1.0

### ISSUE THREAD

**Issue by ia97lies** [dyn4j/dyn4j#177]
My system updated to dyn4j to version: 4.1.0. If I remove a item (I shot the enemy in this case :D) it leads to the following error (the older version didn't had that problem):

Feb 05, 2021 6:58:16 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
java.lang.IllegalStateException
	at java.util.LinkedHashMap$LinkedHashIterator.remove(LinkedHashMap.java:730)
	at org.dyn4j.world.AbstractPhysicsWorld.solveTOI(AbstractPhysicsWorld.java:1400)
	at org.dyn4j.world.AbstractPhysicsWorld.step(AbstractPhysicsWorld.java:1269)
	at org.dyn4j.world.AbstractPhysicsWorld.update(AbstractPhysicsWorld.java:285)
	at org.dyn4j.world.AbstractPhysicsWorld.update(AbstractPhysicsWorld.java:247)
	at ch.artificials.bubble.system.dyn4j.Dyn4jPhysicsSystem.update(Dyn4jPhysicsSystem.java:297)
	at com.jme3.app.state.AppStateManager.update(AppStateManager.java:356)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:255)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:151)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:197)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:232)
	at java.lang.Thread.run(Thread.java:748)

Any idea what I have to change or adapt. I also saw that body.setActive(true) does not exist anymore.

**Comment by wnbittle** [comment]
How/when are you removing the enemy?  That error is emitted at the point where we're checking if two bodies are still overlapping wrt. their swept AABBs.  It could also reach that branch of code if either body didn't exist in the CCD broadphase any more (i.e. being removed).

For Body.setActive(boolean), I think the replacement is Body.setEnabled(boolean).  What version are you coming from?

**Comment by ia97lies** [comment]
I remove the objects simply like this:

    protected void removeDyn4jBody(final Dyn4jBody body, final Entity entity) {
        bodyCache.remove(entity.getId());
        world.removeBody(body);
    }

I just remove it from the physic world.

I went back to version 4.0.2, so just back to the last version.

**Comment by wnbittle** [comment]
Thanks for the additional details - I think I found the issue.  Let me replicate with a unit test and I'll get an update out this evening (ET).

**Comment by ia97lies** [comment]
Thanks a lot :) that was quick!
