### ISSUE TITLE
Cant run the library

### ISSUE THREAD

**Issue by andrewasd** [dyn4j/dyn4j#194]
<!-- 
When i try the dyn4j sample i get this error when compiling 

Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
        The method install() of type AbstractMouseInputHandler must override a superclass method

        at org.dyn4j.samples.framework.input.AbstractMouseInputHandler.install(AbstractMouseInputHandler.java:93)
        at org.dyn4j.samples.framework.SimulationFrame.<init>(SimulationFrame.java:168)
        at org.dyn4j.samples.Maze.<init>(Maze.java:76)
        at org.dyn4j.samples.Maze.main(Maze.java:200)

**To Reproduce**
just run the code with visual studio code 

**Expected behavior**
to  see the gui

**Screenshots/Videos**

**Runtime Information:**
- dyn4j Version: [4.1.3]
 - OS: [Ubuntu 20.04]
 - Java Version: [11]

**Additional context**

**Comment by andrewasd** [comment]
i get this error while compiling the samples of dyn4j, im new to this library and i dont understand well the problem

Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
        The method install() of type AbstractMouseInputHandler must override a superclass method

        at org.dyn4j.samples.framework.input.AbstractMouseInputHandler.install(AbstractMouseInputHandler.java:93)
        at org.dyn4j.samples.framework.SimulationFrame.<init>(SimulationFrame.java:168)
        at org.dyn4j.samples.Maze.<init>(Maze.java:76)
        at org.dyn4j.samples.Maze.main(Maze.java:200)

**Comment by wnbittle** [comment]
What version of Java are you using to compile/run the samples?

**Comment by andrewasd** [comment]
i am using OpenJdk 11 , with vscode , on ubuntu

**Comment by wnbittle** [comment]
Thanks, it looks like VSCode is defaulting to Java 1.5 - which would generate the compilation error above.  Add the `properties` and `build` nodes below to the pom.xml to force it to use Java 6 (or 11 if you prefer).  I'll update the repo this evening to do the same.

```xml
<project 
  xmlns="http://maven.apache.org/POM/4.0.0" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
...
  <properties>
    <maven.compiler.release>6</maven.compiler.release>
  </properties>
  <build>
    <pluginManagement>
        <plugins>
            <plugin>
              <artifactId>maven-compiler-plugin</artifactId>
              <version>3.8.0</version>
          </plugin>
        </plugins>
    </pluginManagement>
  </build>
...
</project>
```

**Comment by wnbittle** [comment]
@andrewasd I pushed a fix for this a day or two ago.  Can you try again when you get a chance?

**Comment by andrewasd** [comment]
Thanks, it's workings now
