### ISSUE TITLE
Triangulation internally generating clockwise polygons

### ISSUE THREAD

**Issue by nsoft** [dyn4j/dyn4j#88]
A sweep line triangulation of the following points succeeds :

````
(9.761856, 2.894968), (9.814371999999999, 2.941328), (9.879956, 2.9670609999999997), (9.950168999999999, 2.975665), (10.020947, 2.972896), (10.090999, 2.962284), (10.160001, 2.946294), (10.224352, 2.917453), (10.287756, 2.8861149999999998), (10.354289, 2.882955), (10.42306, 2.89995), (10.491831, 2.916946), (10.560603, 2.933941), (10.629374, 2.9509369999999997), (10.698146, 2.967932), (10.766917, 2.984928), (10.835689, 3.0019229999999997), (10.902652999999999, 3.023749), (10.966056, 3.055087), (11.02946, 3.0864249999999998), (11.092863999999999, 3.1177639999999998), (11.156269, 3.149102), (11.219673, 3.18044), (11.283076999999999, 3.211778), (11.346480999999999, 3.2431159999999997), (11.409885, 3.274454), (11.470938, 3.309624), (11.528354, 3.350723), (11.585768999999999, 3.391823), (11.643184, 3.432922), (11.700598999999999, 3.474021), (11.758014, 3.51512), (11.815429, 3.5562199999999997), (11.872845, 3.5973189999999997), (11.930259999999999, 3.6384179999999997), (11.987675, 3.6795169999999997), (12.04509, 3.720617), (12.102504999999999, 3.761716), (12.159920999999999, 3.802815), (12.217335, 3.843914), (12.27475, 3.885014), (12.332165999999999, 3.926113), (12.389581, 3.967212), (12.446995, 4.008311), (12.495809999999999, 4.057666), (12.53567, 4.115612), (12.575531999999999, 4.173558), (12.615393, 4.231504999999999), (12.655254, 4.289451), (12.695115, 4.347397), (12.734976, 4.405343), (12.774837, 4.46329), (12.814696999999999, 4.521236), (12.854559, 4.579181999999999), (12.894419, 4.637129), (12.934280999999999, 4.695075), (12.974141, 4.7530209999999995), (13.014002999999999, 4.810967), (13.053863999999999, 4.868914), (13.10245, 4.9170609999999995), (13.159697, 4.9580649999999995), (13.204635, 5.0120059999999995), (13.235349999999999, 5.074993999999999), (13.253463, 5.142634), (13.26161, 5.212177), (13.262213, 5.282213), (13.256893, 5.352073), (13.281281, 5.416812999999999), (13.310070999999999, 5.480848), (13.338861999999999, 5.544881999999999), (13.367652, 5.608917), (13.396441999999999, 5.672950999999999), (13.425232999999999, 5.736986), (13.454023999999999, 5.8010209999999995), (13.482813, 5.865056), (13.511604, 5.929091), (13.540618, 5.993009), (13.575342, 6.054065), (13.605383, 6.117508), (13.630118999999999, 6.183152), (13.650364999999999, 6.250286), (13.666599999999999, 6.3184819999999995), (13.678803, 6.387498), (13.687422999999999, 6.457040999999999), (13.692998, 6.526886999999999), (13.695791, 6.5968979999999995), (13.696048, 6.666963), (13.693999999999999, 6.737000999999999), (13.689857, 6.8069489999999995), (13.683812, 6.8767629999999995), (13.672563, 6.945861), (13.658662, 7.014575), (13.644758999999999, 7.083288), (13.630856, 7.1520019999999995), (13.616954999999999, 7.2207159999999995), (13.5985, 7.288234), (13.576082999999999, 7.354711999999999), (13.553666999999999, 7.421189999999999), (13.53125, 7.4876689999999995), (13.508833, 7.5541469999999995), (13.47304, 7.614159), (13.433719, 7.672464), (13.394397, 7.730769), (13.355075999999999, 7.789073999999999), (13.315754, 7.847379999999999), (13.276432999999999, 7.905685), (13.237110999999999, 7.963991), (13.193520999999999, 8.019065), (13.146841, 8.071802), (13.100159999999999, 8.124537), (13.053479999999999, 8.177273999999999), (13.006801, 8.23001), (12.960121, 8.282746999999999), (12.91344, 8.335483), (12.86676, 8.388219), (12.820081, 8.440954999999999), (12.773401, 8.493692), (12.72672, 8.546427999999999), (12.660881, 8.571221), (12.594036, 8.594543), (12.527189, 8.617865), (12.460341999999999, 8.641187), (12.393495, 8.66451), (12.326647999999999, 8.687832), (12.259801, 8.711153999999999), (12.192955999999999, 8.734475999999999), (12.126109, 8.757798), (12.059261999999999, 8.781120999999999), (11.992415, 8.804442), (11.925568, 8.827764), (11.858723, 8.851087), (11.791876, 8.874409), (11.725029, 8.897731), (11.658182, 8.921052999999999), (11.591334999999999, 8.944374999999999), (11.524488999999999, 8.967698), (11.454464999999999, 8.977869), (11.384172, 8.986932999999999), (11.31388, 8.995996), (11.243587, 9.005059), (11.173295, 9.014123), (11.103002, 9.023185999999999), (11.03271, 9.032249), (10.962417, 9.041312999999999), (10.892123999999999, 9.050376), (10.821831999999999, 9.05944), (10.751539, 9.068503), (10.681084, 9.075819), (10.610294999999999, 9.079500999999999), (10.539505, 9.083185), (10.468715, 9.086867), (10.397924999999999, 9.090551), (10.327135, 9.094233), (10.256345, 9.097916999999999), (10.185554999999999, 9.1016)
````
 but adding one more point: `(10.114765, 9.105283)` will cause an exception :
````
java.lang.IllegalArgumentException: A polygon must have Counter-Clockwise vertex winding.
	at org.dyn4j.geometry.Polygon.validate(Polygon.java:143)
	at org.dyn4j.geometry.Polygon.<init>(Polygon.java:96)
	at org.dyn4j.geometry.Triangle.<init>(Triangle.java:56)
	at org.dyn4j.geometry.Geometry.createTriangle(Geometry.java:608)
	at org.dyn4j.geometry.decompose.DoubleEdgeList.getTriangulation(DoubleEdgeList.java:437)
	at org.dyn4j.geometry.decompose.SweepLine.triangulate(SweepLine.java:81)
````
The added point is very clearly just one more small step forward in the same direction as the prior points, and plotting the points here: http://www.shodor.org/interactivate/activities/SimplePlot/ shows this to be very unremarkable. Furthermore in Sweepline() one passes through this code: 
````
		// get the winding order
		double winding = Geometry.getWinding(points);
		
		// reverse the array if the points are in clockwise order
		if (winding < 0.0) {
			Geometry.reverseWinding(points);
		}
````
So it seems that something deep inside in the triangulation is creating bad polygons....

**Comment by wnbittle** [comment]
What version of the library are you working with?  There are a lot of bug fixes coming, especially with SweepLine in the next release.  

Any way you can try the latest code from source?  I tried with with latest and I'm getting a valid triangulation.

**Comment by wnbittle** [comment]
This seems to be working properly on latest source.  Please reopen if you still have the issue after trying latest.

**Comment by nsoft** [comment]
Yeah I just did this test as well and the latest seems to solve it.
